=== open-mpi/ompi/opal/mca/hwloc/hwloc2000/hwloc/hwloc/hwloc2.dtd
<!--
  Copyright © 2009      CNRS
  Copyright © 2009-2017 Inria.  All rights reserved.
  Copyright © 2009-2011 Université Bordeaux.
  See COPYING in top-level directory.

  This is the DTD for hwloc v2.x XMLs.
 -->

<!ELEMENT topology (object+,distances2*)>
<!ATTLIST topology version CDATA "">

<!ELEMENT object (page_type*,info*,userdata*,object*)>
<!ATTLIST object type (Machine | Misc | Group | NUMANode | Package | L1Cache | L2Cache | L3Cache | L4Cache | L5Cache | L1iCache | L2iCache | L3iCache | Core | PU | Bridge | PCIDev | OSDev) #REQUIRED>
<!ATTLIST object subtype CDATA "" >
<!ATTLIST object os_index CDATA "-1" >
<!ATTLIST object gp_index CDATA "-1" >
<!ATTLIST object name CDATA "" >
<!ATTLIST object local_memory CDATA "0" >
<!ATTLIST object cache_size CDATA "0" >
<!ATTLIST object cache_linesize CDATA "0" >
<!ATTLIST object cache_associativity CDATA "0" >
<!ATTLIST object cache_type CDATA "0" >
<!ATTLIST object cpuset CDATA "0" >
<!ATTLIST object complete_cpuset CDATA "" >
<!ATTLIST object allowed_cpuset CDATA "" >
<!ATTLIST object nodeset CDATA "" >
<!ATTLIST object complete_nodeset CDATA "" >
<!ATTLIST object allowed_nodeset CDATA "" >
<!ATTLIST object depth CDATA "-1" >
<!ATTLIST object kind CDATA "0" >
<!ATTLIST object subkind CDATA "0" >
<!ATTLIST object bridge_type CDATA "" >
<!ATTLIST object bridge_pci CDATA "" >
<!ATTLIST object pci_busid CDATA "" >
<!ATTLIST object pci_type CDATA "" >
<!ATTLIST object pci_link_speed CDATA "0." >
<!ATTLIST object osdev_type CDATA "" >

<!ELEMENT page_type EMPTY>
<!ATTLIST page_type size CDATA #REQUIRED>
<!ATTLIST page_type count CDATA #REQUIRED>

<!ELEMENT info EMPTY>
<!ATTLIST info name CDATA #REQUIRED>
<!ATTLIST info value CDATA #REQUIRED>

<!ELEMENT distances2 (indexes+,u64values+)>
<!ATTLIST distances2 type CDATA #REQUIRED>
<!ATTLIST distances2 nbobjs CDATA #REQUIRED>
<!ATTLIST distances2 indexing CDATA #REQUIRED>
<!ATTLIST distances2 kind CDATA #REQUIRED>

<!ELEMENT indexes (#PCDATA)>
<!ATTLIST indexes length CDATA #REQUIRED>

<!ELEMENT u64values (#PCDATA)>
<!ATTLIST u64values length CDATA #REQUIRED>

<!ELEMENT userdata (#PCDATA)>
<!ATTLIST userdata name CDATA "" >
<!ATTLIST userdata length CDATA "0" >
<!ATTLIST userdata encoding CDATA "" >

=== open-mpi/ompi/opal/mca/hwloc/hwloc2000/hwloc/tests/hwloc/xml/8ia64-2n2s2c+1n.v1tov2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x000f000f" complete_cpuset="0x00ff00ff" allowed_cpuset="0x000f000f" nodeset="0x00010005" complete_nodeset="0x00010005" allowed_nodeset="0x00010005" gp_index="1">
    <info name="Backend" value="Linux"/>
    <info name="Architecture" value="ia64"/>
    <info name="hwlocVersion" value="1.11.8"/>
    <info name="ProcessName" value="lstopo"/>
    <object type="Group" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="28" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" local_memory="102458458112"/>
      <object type="Package" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5">
          <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7">
          <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
        </object>
      </object>
      <object type="Package" os_index="1" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10">
          <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="12">
          <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="13"/>
        </object>
      </object>
    </object>
    <object type="Group" cpuset="0x000f0000" complete_cpuset="0x000f0000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="29" kind="1001" subkind="0">
      <object type="NUMANode" os_index="2" cpuset="0x000f0000" complete_cpuset="0x000f0000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="14" local_memory="103012106240"/>
      <object type="Package" os_index="131072" cpuset="0x00030000" complete_cpuset="0x00030000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="16">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00010000" complete_cpuset="0x00010000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="17">
          <object type="PU" os_index="16" cpuset="0x00010000" complete_cpuset="0x00010000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="18"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00020000" complete_cpuset="0x00020000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="19">
          <object type="PU" os_index="17" cpuset="0x00020000" complete_cpuset="0x00020000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="20"/>
        </object>
      </object>
      <object type="Package" os_index="131073" cpuset="0x000c0000" complete_cpuset="0x000c0000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="21">
        <info name="CPUVendor" value="GenuineIntel"/>
        <info name="CPUFamilyNumber" value="32"/>
        <info name="CPUModelNumber" value="1"/>
        <info name="CPUModel" value="Dual-Core Intel(R) Itanium(R) Processor 9140N"/>
        <object type="Core" os_index="0" cpuset="0x00040000" complete_cpuset="0x00040000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="22">
          <object type="PU" os_index="18" cpuset="0x00040000" complete_cpuset="0x00040000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="23"/>
        </object>
        <object type="Core" os_index="1" cpuset="0x00080000" complete_cpuset="0x00080000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="24">
          <object type="PU" os_index="19" cpuset="0x00080000" complete_cpuset="0x00080000" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="25"/>
        </object>
      </object>
    </object>
    <object type="Group" cpuset="0x0" complete_cpuset="0x0" nodeset="0x00010000" complete_nodeset="0x00010000" gp_index="30" kind="1001" subkind="0">
      <object type="NUMANode" os_index="16" cpuset="0x0" complete_cpuset="0x0" nodeset="0x00010000" complete_nodeset="0x00010000" gp_index="26" local_memory="1044660224"/>
    </object>
  </object>
  <distances2 type="NUMANode" nbobjs="3" kind="5" indexing="os">
    <indexes length="7">0 2 16 </indexes>
    <u64values length="27">10 17 17 17 17 10 14 14 14 </u64values>
  </distances2>
</topology>

=== open-mpi/ompi/opal/mca/hwloc/hwloc2000/hwloc/tests/hwloc/xml/16em64t-4s2c2t-offlines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x0000905b" complete_cpuset="0x0000ffff" allowed_cpuset="0x0000905b" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001" gp_index="1">
    <object type="NUMANode" os_index="0" cpuset="0x0000905b" complete_cpuset="0x0000ffff" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2"/>
    <object type="Package" os_index="0" cpuset="0x00001011" complete_cpuset="0x00001111" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3">
      <object type="L3Cache" cpuset="0x00001011" complete_cpuset="0x00001111" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4" cache_size="4194304" depth="3" cache_linesize="0" cache_associativity="0" cache_type="0">
        <object type="L2Cache" cpuset="0x00000001" complete_cpuset="0x00000101" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5" cache_size="1048576" depth="2" cache_linesize="0" cache_associativity="0" cache_type="0">
          <object type="L1Cache" cpuset="0x00000001" complete_cpuset="0x00000101" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6" cache_size="16384" depth="1" cache_linesize="0" cache_associativity="0" cache_type="1">
            <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000101" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7">
              <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
            </object>
          </object>
        </object>
        <object type="L2Cache" cpuset="0x00001010" complete_cpuset="0x00001010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9" cache_size="1048576" depth="2" cache_linesize="0" cache_associativity="0" cache_type="0">
          <object type="L1Cache" cpuset="0x00001010" complete_cpuset="0x00001010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10" cache_size="16384" depth="1" cache_linesize="0" cache_associativity="0" cache_type="1">
            <object type="Core" os_index="1" cpuset="0x00001010" complete_cpuset="0x00001010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11">
              <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="12"/>
              <object type="PU" os_index="12" cpuset="0x00001000" complete_cpuset="0x00001000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="13"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="1" cpuset="0x00000002" complete_cpuset="0x00002222" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="14">
      <object type="L3Cache" cpuset="0x00000002" complete_cpuset="0x00002222" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="15" cache_size="4194304" depth="3" cache_linesize="0" cache_associativity="0" cache_type="0">
        <object type="L2Cache" cpuset="0x00000002" complete_cpuset="0x00000202" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="16" cache_size="1048576" depth="2" cache_linesize="0" cache_associativity="0" cache_type="0">
          <object type="L1Cache" cpuset="0x00000002" complete_cpuset="0x00000202" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="17" cache_size="16384" depth="1" cache_linesize="0" cache_associativity="0" cache_type="1">
            <object type="Core" os_index="0" cpuset="0x00000002" complete_cpuset="0x00000202" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="18">
              <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="19"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="2" cpuset="0x00000040" complete_cpuset="0x00004444" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="30">
      <object type="L3Cache" cpuset="0x00000040" complete_cpuset="0x00004444" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="31" cache_size="4194304" depth="3" cache_linesize="0" cache_associativity="0" cache_type="0">
        <object type="L2Cache" cpuset="0x00000040" complete_cpuset="0x00004040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="32" cache_size="1048576" depth="2" cache_linesize="0" cache_associativity="0" cache_type="0">
          <object type="L1Cache" cpuset="0x00000040" complete_cpuset="0x00004040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="33" cache_size="16384" depth="1" cache_linesize="0" cache_associativity="0" cache_type="1">
            <object type="Core" os_index="1" cpuset="0x00000040" complete_cpuset="0x00004040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="34">
              <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="35"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="3" cpuset="0x00008008" complete_cpuset="0x00008888" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="20">
      <object type="L3Cache" cpuset="0x00008008" complete_cpuset="0x00008888" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="21" cache_size="4194304" depth="3" cache_linesize="0" cache_associativity="0" cache_type="0">
        <object type="L2Cache" cpuset="0x00000008" complete_cpuset="0x00000808" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="22" cache_size="1048576" depth="2" cache_linesize="0" cache_associativity="0" cache_type="0">
          <object type="L1Cache" cpuset="0x00000008" complete_cpuset="0x00000808" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="23" cache_size="16384" depth="1" cache_linesize="0" cache_associativity="0" cache_type="1">
            <object type="Core" os_index="0" cpuset="0x00000008" complete_cpuset="0x00000808" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="24">
              <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="25"/>
            </object>
          </object>
        </object>
        <object type="L2Cache" cpuset="0x00008000" complete_cpuset="0x00008080" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="26" cache_size="1048576" depth="2" cache_linesize="0" cache_associativity="0" cache_type="0">
          <object type="L1Cache" cpuset="0x00008000" complete_cpuset="0x00008080" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="27" cache_size="16384" depth="1" cache_linesize="0" cache_associativity="0" cache_type="1">
            <object type="Core" os_index="1" cpuset="0x00008000" complete_cpuset="0x00008080" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="28">
              <object type="PU" os_index="15" cpuset="0x00008000" complete_cpuset="0x00008000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="29"/>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
</topology>

=== open-mpi/ompi/opal/mca/hwloc/hwloc2000/hwloc/tests/hwloc/xml/2intel64-1n2c-numaroot.v1tov2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" cpuset="0x00000003" complete_cpuset="0x00000003" allowed_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001" gp_index="2">
    <info name="hwlocVersion" value="v1.11-20170902.0906.git16cb39b"/>
    <info name="ProcessName" value="lstopo-no-graphics"/>
    <object type="NUMANode" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="1" local_memory="2147074048">
      <page_type size="4096" count="0"/>
      <info name="hwlocVersion" value="v1.11-20170902.0906.git16cb39b"/>
      <info name="ProcessName" value="lstopo-no-graphics"/>
    </object>
    <object type="Package" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3">
      <info name="CPUModel" value="QEMU Virtual CPU version (cpu64-rhel6)"/>
      <info name="CPUVendor" value="GenuineIntel"/>
      <info name="CPUFamilyNumber" value="6"/>
      <info name="CPUModelNumber" value="13"/>
      <info name="CPUStepping" value="3"/>
      <object type="L2Cache" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4" cache_size="4194304" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <info name="Inclusive" value="0"/>
        <object type="L1Cache" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
          <info name="Inclusive" value="0"/>
          <object type="L1iCache" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
            <info name="Inclusive" value="0"/>
            <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7">
              <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9">
      <info name="CPUModel" value="QEMU Virtual CPU version (cpu64-rhel6)"/>
      <info name="CPUVendor" value="GenuineIntel"/>
      <info name="CPUFamilyNumber" value="6"/>
      <info name="CPUModelNumber" value="13"/>
      <info name="CPUStepping" value="3"/>
      <object type="L2Cache" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10" cache_size="4194304" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <info name="Inclusive" value="0"/>
        <object type="L1Cache" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
          <info name="Inclusive" value="0"/>
          <object type="L1iCache" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="12" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
            <info name="Inclusive" value="0"/>
            <object type="Core" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="13">
              <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="14"/>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
</topology>
